// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeLvShlrZR6gJfi3qizKjItapyab3jeFc',
    appId: '1:184899046648:web:37dc0e7a0b331540f4ff0d',
    messagingSenderId: '184899046648',
    projectId: 'chat-app-c826f',
    authDomain: 'chat-app-c826f.firebaseapp.com',
    storageBucket: 'chat-app-c826f.firebasestorage.app',
    measurementId: 'G-4QENP9L4FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWgNH6rnXwG_Tmzc-eFK6qnNEWQocf6uA',
    appId: '1:184899046648:android:410864be267e181ef4ff0d',
    messagingSenderId: '184899046648',
    projectId: 'chat-app-c826f',
    storageBucket: 'chat-app-c826f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJuqe7sXJpPukEvwxiTJ4K3jJfV3cs3tw',
    appId: '1:184899046648:ios:3ec2b609f0b7cf7ef4ff0d',
    messagingSenderId: '184899046648',
    projectId: 'chat-app-c826f',
    storageBucket: 'chat-app-c826f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJuqe7sXJpPukEvwxiTJ4K3jJfV3cs3tw',
    appId: '1:184899046648:ios:3ec2b609f0b7cf7ef4ff0d',
    messagingSenderId: '184899046648',
    projectId: 'chat-app-c826f',
    storageBucket: 'chat-app-c826f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeLvShlrZR6gJfi3qizKjItapyab3jeFc',
    appId: '1:184899046648:web:a596d6f1c987ed97f4ff0d',
    messagingSenderId: '184899046648',
    projectId: 'chat-app-c826f',
    authDomain: 'chat-app-c826f.firebaseapp.com',
    storageBucket: 'chat-app-c826f.firebasestorage.app',
    measurementId: 'G-WYJDLQ2RRD',
  );
}
